### ISSUE TITLE
 No module named 'data.data_sampler'

### ISSUE THREAD

**Issue by Le2Hu** [CS-GangXu/TMNet#1]
Is 'data' a folder to be uploaded or a module can be installed?
https://github.com/CS-GangXu/TMNet/blob/992ff0d163760722eecacc7f065bcb85aa3ad06c/codes/train.py#L10
https://github.com/CS-GangXu/TMNet/blob/992ff0d163760722eecacc7f065bcb85aa3ad06c/codes/train.py#L14
https://github.com/CS-GangXu/TMNet/blob/992ff0d163760722eecacc7f065bcb85aa3ad06c/codes/train.py#L18

**Comment by CS-GangXu** [comment]
@Le2Hu  I'm sorry for this error, we have uploaded this code in the latest version.
