### ISSUE TITLE
Can you specified which Vimeo7_train_keys.pkl should be placed in the higher directiory?

### ISSUE THREAD

**Issue by rogerchenrc** [CS-GangXu/TMNet#16]
Hi, I want to ask question regarding your direction "Please copy the Vimeo7_train_keys.pkl into the folder with higher level. After the aboved operations, we assume that you can get a folder with the following structure". Since there are two Vimeo7_train_keys.pkl file, one generated by GT and another by LR7. I want to ask which one should I be placed in higher level directory?

Best regards,
KHC

**Comment by CS-GangXu** [comment]
Hi, @rogerchenrc , either of these two Vimeo7_train_keys.pkl can be put into the higher level directory.
