### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by nadimra** [CS-GangXu/TMNet#17]
Hello,

I have tried running the model on a custom dataset, but I come across this error:

RuntimeError: CUDA out of memory. Tried to allocate 938.00 MiB (GPU 0; 11.93 GiB total capacity; 1.63 GiB already allocated; 673.69 MiB free; 2.44 GiB reserved in total by PyTorch)

I guess one way to solve this would be to reduce the resolution of my dataset, but is there an alternative way?

**Comment by CS-GangXu** [comment]
Hi, @nadimra , please try reducing the number of the resblock and the channel number to build a model with less parameters. Then you can train this model using the provided datasets and your own dataset.
