### ISSUE TITLE
Running Evaluation on Fast/Medium/Slow

### ISSUE THREAD

**Issue by rogerchenrc** [CS-GangXu/TMNet#21]
Hello, just want to ask during evaluation of fast, medium and slow Vimeo dataset, is it required to change any util code? If yes, which part is necessary to change? I am able to run and evaluate Vid4 dataset, but doesn't seems to know why when running fast/medium/slow vimeo test dataset even I change the glob.glob access, the LR/ HR doesn't seems to be aligning to evaluate. If I keep the original code, the read_image will not read any path, since the original code only have access till , "./datasets/vimeo/LR/00001". Some help will be appreciated! Thank you

**Comment by CS-GangXu** [comment]
Hi, @rogerchenrc 
1) you only need to change `test_args['data_mode']` and `test_args['dataset_folder']` in `test_single_frame.py`.
2) can you provide the structure of the test set folder of vimeo in your device? And the default path of the folder should be:
```
# test_args['data_mode'] = 'vimeo_fast'
# test_args['dataset_folder'] =  './datasets/vimeo-90k_septuplet/fast_of_test/LR/*'

# test_args['data_mode'] = 'vimeo_medium'
# test_args['dataset_folder'] =  './datasets/vimeo-90k_septuplet/medium_of_test/LR/*'

# test_args['data_mode'] = 'vimeo_slow'
# test_args['dataset_folder'] =  './datasets/vimeo-90k_septuplet/slow_of_test/LR/*'
```

**Comment by rogerchenrc** [comment]
The structure of the test folder is as follow, and yes I have change the default path accordingly to my path but still doesn't work
![Screenshot from 2022-06-29 01-19-56](https://user-images.githubusercontent.com/56882421/176325505-e54aa66b-57a6-4d2c-b75f-e257a18ca04b.png)

**Comment by CS-GangXu** [comment]
I'm sorry that I didn't explain the detailed structure in the Vimeo evaluation clearly.
You should reorganize the structure of the test data with the following structure:
```
├── fast_of_test
│   ├── HR
│          └── 00001_0266
│   └── LR
│          └── 00001_0266
```
