### ISSUE TITLE
测试代码问题

### ISSUE THREAD

**Issue by silence-moon** [CS-GangXu/TMNet#6]
你好，感谢您的工作！在运行您的测试代码的时候，我发现checkpoints目录下没有相关的模型，主页上也没有介绍，请问在哪可以获取已经训练好的模型呢？

**Comment by CS-GangXu** [comment]
@silence-moon Our pretrained models (`tmnet_single_frame.pth` and `tmnet_multiple_frames.pth`) can be downloaded via [Link](https://drive.google.com/drive/folders/1PjXClB-S8pyB6y1UWJQnZK7fela5Lcu1). After you download the pretrained models, you can put them into the `$ROOT/checkpoints` folder.

**Comment by silence-moon** [comment]
谢谢啊





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CS-GangXu/TMNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月26日(星期天) 下午3:51
***@***.***&gt;;
抄送:&nbsp;"月影 无痕 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [CS-GangXu/TMNet] 测试代码问题 (#6)





 
@silence-moon Our pretrained models (tmnet_single_frame.pth and tmnet_multiple_frames.pth) can be downloaded via Link. After you download the pretrained models, you can put them into the $ROOT/checkpoints folder.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by silence-moon** [comment]
你好，谷歌网盘打开后下载不了，请问还有其他的传输方式吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CS-GangXu/TMNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月26日(星期天) 下午3:51
***@***.***&gt;;
抄送:&nbsp;"月影 无痕 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [CS-GangXu/TMNet] 测试代码问题 (#6)





 
@silence-moon Our pretrained models (tmnet_single_frame.pth and tmnet_multiple_frames.pth) can be downloaded via Link. After you download the pretrained models, you can put them into the $ROOT/checkpoints folder.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CS-GangXu** [comment]
I'm sorry.
Google Drive is the only way to download the pretrained model.

**Comment by silence-moon** [comment]
okok，the&nbsp;pretrained model has been downloaded just now,thanks thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gang ***@***.***&gt;; 
发送时间: 2021年9月26日(星期天) 下午4:18
收件人: ***@***.***&gt;; 
抄送: "月影 无痕 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CS-GangXu/TMNet] 测试代码问题 (#6)





 
I'm sorry.
 Google Drive is the only way to download the pretrained model.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CS-GangXu** [comment]
You're welcome!
